'use client';

import React from 'react';
import { useEduPath } from '../store/useEduPathStore';
import { Sparkles, X, ArrowRight, Zap, Clock, ShieldAlert } from 'lucide-react';

export const WhyPlanChangedModal: React.FC = () => {
  const {
    isWhyPlanChangedModalOpen,
    setIsWhyPlanChangedModalOpen,
    latestDecision,
    setActiveTab
  } = useEduPath();

  if (!isWhyPlanChangedModalOpen || !latestDecision) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="bg-[#0f172a] border border-amber-500/50 rounded-2xl max-w-2xl w-full p-6 md:p-8 shadow-2xl shadow-amber-500/10 space-y-6 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-amber-500/5 rounded-full blur-3xl pointer-events-none"></div>

        
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-amber-500/20 border border-amber-500/40 flex items-center justify-center text-amber-400">
              <Zap className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-xl font-bold text-white tracking-tight">
                  Why did my plan change?
                </h3>
                <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-amber-500/20 text-amber-300 border border-amber-500/30">
                  Adaptive Agent
                </span>
              </div>
              <p className="text-xs text-slate-400">
                Transparent decision receipt generated by the Adaptive Planner Agent at {latestDecision.timestamp}.
              </p>
            </div>
          </div>
          <button
            onClick={() => setIsWhyPlanChangedModalOpen(false)}
            className="text-slate-400 hover:text-white p-1 rounded-lg hover:bg-white/5 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* 4 STAGES OF AI REASONING */}
        <div className="space-y-3.5 text-xs">
          {/* 1. TRIGGER */}
          <div className="p-3.5 rounded-xl bg-black/30 border border-slate-800 space-y-1">
            <span className="font-bold text-amber-400 uppercase tracking-wider text-[10px] flex items-center gap-1.5">
              <ShieldAlert className="w-3.5 h-3.5" /> 1. Trigger Event
            </span>
            <p className="text-slate-200 leading-relaxed">{latestDecision.triggerReason}</p>
          </div>

          {/* 2. EVIDENCE */}
          <div className="p-3.5 rounded-xl bg-black/30 border border-slate-800 space-y-1">
            <span className="font-bold text-blue-400 uppercase tracking-wider text-[10px] flex items-center gap-1.5">
              <Sparkles className="w-3.5 h-3.5" /> 2. Diagnostic Telemetry Evidence
            </span>
            <p className="text-slate-200 leading-relaxed">{latestDecision.evidenceSummary}</p>
          </div>

          {/* 3. DECISION */}
          <div className="p-3.5 rounded-xl bg-black/30 border border-slate-800 space-y-1">
            <span className="font-bold text-purple-400 uppercase tracking-wider text-[10px] flex items-center gap-1.5">
              <Clock className="w-3.5 h-3.5" /> 3. Architectural Decision
            </span>
            <p className="text-slate-200 leading-relaxed">{latestDecision.decisionText}</p>
          </div>

          {/* 4. ACTION & IMPACT */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <div className="p-3.5 rounded-xl bg-emerald-950/20 border border-emerald-500/30 space-y-1">
              <span className="font-bold text-emerald-400 uppercase tracking-wider text-[10px] block">
                4. Action Taken
              </span>
              <p className="text-emerald-200 leading-relaxed">{latestDecision.actionTaken}</p>
            </div>
            <div className="p-3.5 rounded-xl bg-amber-950/20 border border-amber-500/30 space-y-1">
              <span className="font-bold text-amber-400 uppercase tracking-wider text-[10px] block">
                5. Schedule Impact
              </span>
              <p className="text-amber-200 leading-relaxed">{latestDecision.impactSummary}</p>
            </div>
          </div>
        </div>

        {/* ACTIONS */}
        <div className="flex items-center justify-between pt-3 border-t border-slate-800">
          <button
            onClick={() => setIsWhyPlanChangedModalOpen(false)}
            className="px-4 py-2 rounded-xl text-xs font-semibold text-slate-400 hover:text-white transition"
          >
            Close Receipt
          </button>

          <button
            onClick={() => {
              setIsWhyPlanChangedModalOpen(false);
              setActiveTab('path');
            }}
            className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-amber-500 hover:bg-amber-400 text-black font-bold text-xs transition shadow-lg shadow-amber-500/20"
          >
            <span>Inspect Injected Recovery Module</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </div>
      </div>
    </div>
  );
};
