import { PracticeQuestion } from '../types';

export const COMPREHENSIVE_QUESTION_BANK: PracticeQuestion[] = [
  {
    id: 'q-sql-1',
    skillId: 'sql',
    skillName: 'SQL & Relational DB',
    subConcept: 'INNER JOIN vs LEFT JOIN',
    prompt: 'You have a `users` table and an `orders` table. You need to return all registered users, including those who have never placed an order. Which SQL join query accomplishes this?',
    type: 'mcq',
    options: [
      'SELECT * FROM users INNER JOIN orders ON users.id = orders.user_id;',
      'SELECT * FROM users LEFT JOIN orders ON users.id = orders.user_id;',
      'SELECT * FROM orders RIGHT JOIN users ON orders.id = users.id WHERE orders.id IS NOT NULL;',
      'SELECT * FROM users CROSS JOIN orders;'
    ],
    correctIndex: 1,
    explanation: 'A LEFT JOIN returns all rows from the left table (`users`), along with matched records from the right table (`orders`). For users with no orders, the order fields will contain NULL.',
    hint: 'Think about which table is on the "left" of the query and must preserve all its records even if there is no match.',
    difficulty: 'intermediate'
  },
  {
    id: 'q-sql-2',
    skillId: 'sql',
    skillName: 'SQL & Relational DB',
    subConcept: 'Aggregation with JOINs',
    prompt: 'Look at the query below. It attempts to find the total revenue per user, but users with zero orders are disappearing from the result. Why?\n\nSELECT u.name, SUM(o.amount)\nFROM users u\nJOIN orders o ON u.id = o.user_id\nGROUP BY u.name;',
    type: 'debugging',
    options: [
      'The GROUP BY statement should be grouped by o.amount instead of u.name.',
      'A plain JOIN defaults to an INNER JOIN, discarding users without matching rows in orders.',
      'SUM() cannot be used with JOIN statements in standard SQL.',
      'The ON condition syntax is invalid for relational databases.'
    ],
    correctIndex: 1,
    explanation: 'An unqualified JOIN is an INNER JOIN. It filters out any user who has 0 rows in the orders table. Changing it to `LEFT JOIN` and using `COALESCE(SUM(o.amount), 0)` keeps all users.',
    hint: 'What kind of join does SQL execute when you omit the words INNER or OUTER?',
    difficulty: 'intermediate'
  },
  {
    id: 'q-sql-3',
    skillId: 'sql',
    skillName: 'SQL & Relational DB',
    subConcept: 'WHERE vs HAVING Clause',
    prompt: 'What is the primary difference between the WHERE and HAVING clauses in an SQL query?',
    type: 'mcq',
    options: [
      'WHERE filters individual rows before aggregation occurs, while HAVING filters grouped rows after aggregation.',
      'HAVING is used exclusively for string matching, whereas WHERE is used for numerical comparisons.',
      'WHERE can only be used with primary keys, whereas HAVING works on any indexed column.',
      'There is no difference; HAVING is just legacy syntax for WHERE.'
    ],
    correctIndex: 0,
    explanation: 'WHERE filters individual records before any grouping (GROUP BY) takes place. HAVING filters summary rows generated by aggregate functions (e.g. `HAVING COUNT(*) > 5`).',
    hint: 'Think about when aggregate functions like COUNT() and AVG() are calculated in SQL execution order.',
    difficulty: 'beginner'
  },
  {
    id: 'q-sql-4',
    skillId: 'sql',
    skillName: 'SQL & Relational DB',
    subConcept: 'B-Tree Index Invalidation',
    prompt: 'Which of the following database column operations will typically PREVENT a standard B-Tree index from being utilized in a WHERE clause?',
    type: 'mcq',
    options: [
      'Filtering with an equality operator, such as `WHERE email = \'alex@example.com\'`',
      'Filtering with a range condition, such as `WHERE created_at > \'2025-01-01\'`',
      'Applying an unindexed function on the column, such as `WHERE LOWER(email) = \'alex@example.com\'`',
      'Sorting by the indexed column using `ORDER BY email ASC`'
    ],
    correctIndex: 2,
    explanation: 'Wrapping an indexed column in a function like `LOWER(email)` prevents the query planner from using the index, requiring a full table scan unless a functional/expression index is explicitly created.',
    hint: 'Can the database look up the raw B-Tree index if you mutate every value with a function at runtime?',
    difficulty: 'advanced'
  },
  {
    id: 'q-sql-5',
    skillId: 'sql',
    skillName: 'SQL & Relational DB',
    subConcept: 'ACID Transactions (Atomicity)',
    prompt: 'In a relational database transaction adhering to ACID properties, what does "Atomicity" guarantee?',
    type: 'mcq',
    options: [
      'Transactions are executed with atomic single-threaded hardware locks.',
      'All operations within the transaction succeed completely, or the entire transaction is rolled back with no partial changes.',
      'Data written to the database is replicated to multiple disk partitions immediately.',
      'Concurrent transactions never see uncommitted changes from other active transactions.'
    ],
    correctIndex: 1,
    explanation: 'Atomicity ensures "all-or-nothing" execution. If any single statement in the transaction fails, all previously executed statements within that transaction are rolled back.',
    hint: 'Think of an atom as indivisible: you cannot have half of a transaction committed.',
    difficulty: 'intermediate'
  },
  {
    id: 'q-sql-6',
    skillId: 'sql',
    skillName: 'SQL & Relational DB',
    subConcept: 'Anti-Join (Finding Unmatched Records)',
    prompt: 'Which query correctly finds all `customers` who have NO corresponding records in the `invoices` table?',
    type: 'mcq',
    options: [
      'SELECT c.id FROM customers c JOIN invoices i ON c.id = i.customer_id WHERE i.id = NULL;',
      'SELECT c.id FROM customers c LEFT JOIN invoices i ON c.id = i.customer_id WHERE i.id IS NULL;',
      'SELECT c.id FROM customers c RIGHT JOIN invoices i ON c.id = i.customer_id WHERE c.id IS NULL;',
      'SELECT c.id FROM customers c INNER JOIN invoices i ON c.id = i.customer_id HAVING COUNT(i.id) = 0;'
    ],
    correctIndex: 1,
    explanation: 'A LEFT JOIN keeps all customers. For customers without invoices, `i.id` will be NULL. Thus, `WHERE i.id IS NULL` isolates customers with no orders. Also note that `WHERE i.id = NULL` is invalid because NULL comparisons require `IS NULL`.',
    hint: 'Remember: in SQL, you cannot check null equality with `= NULL`; you must use `IS NULL`.',
    difficulty: 'intermediate'
  },
  {
    id: 'q-sql-7',
    skillId: 'sql',
    skillName: 'SQL & Relational DB',
    subConcept: 'Foreign Key Referential Integrity',
    prompt: 'What is the primary function of a FOREIGN KEY constraint in relational schema design?',
    type: 'mcq',
    options: [
      'To encrypt sensitive table data when storing records on remote storage volumes.',
      'To enforce referential integrity by ensuring a column value matches an existing primary key in another table.',
      'To automatically double the read speed of queries by creating a clustered hash index.',
      'To allow null values in a primary key column.'
    ],
    correctIndex: 1,
    explanation: 'A foreign key constraint enforces referential integrity between two tables, preventing orphan rows and guaranteeing that relationships between records remain valid.',
    hint: 'Foreign keys link child tables back to parent tables to avoid orphan records.',
    difficulty: 'beginner'
  },
  {
    id: 'q-js-1',
    skillId: 'js',
    skillName: 'JavaScript (ES6+)',
    subConcept: 'Event Loop & Microtask Queue',
    prompt: 'Consider the following JavaScript snippet:\n\nconsole.log("1");\nsetTimeout(() => console.log("2"), 0);\nPromise.resolve().then(() => console.log("3"));\nconsole.log("4");\n\nWhat is the exact logged order?',
    type: 'mcq',
    options: [
      '1, 2, 3, 4',
      '1, 4, 2, 3',
      '1, 4, 3, 2',
      '1, 3, 4, 2'
    ],
    correctIndex: 2,
    explanation: '1 and 4 execute synchronously. The Promise resolution enters the microtask queue, which is drained immediately after synchronous execution, printing 3. Finally, the setTimeout macrotask runs from the task queue, printing 2.',
    hint: 'Microtasks (Promises) always take priority over macrotasks (setTimeout) after the current execution stack empties.',
    difficulty: 'intermediate'
  },
  {
    id: 'q-js-2',
    skillId: 'js',
    skillName: 'JavaScript (ES6+)',
    subConcept: 'Lexical Closures',
    prompt: 'What is a closure in JavaScript?',
    type: 'mcq',
    options: [
      'A function bundled together with references to its lexical environment, allowing it to access outer variables even after the outer function has returned.',
      'A method that automatically cleans up unused variables from the garbage collector heap.',
      'A syntax keyword used to terminate a loop or switch case block.',
      'An encrypted asynchronous wrapper around a WebAssembly module.'
    ],
    correctIndex: 0,
    explanation: 'A closure is created when an inner function retains access to variables declared in its outer enclosing scope, persisting those references even after the outer function finishes execution.',
    hint: 'Think of an inner function remembering the variables of the factory function that created it.',
    difficulty: 'beginner'
  },
  {
    id: 'q-js-3',
    skillId: 'js',
    skillName: 'JavaScript (ES6+)',
    subConcept: 'Loose vs Strict Equality',
    prompt: 'What are the evaluation results of `0 == "0"` and `0 === "0"` in JavaScript?',
    type: 'mcq',
    options: [
      'true and true',
      'false and false',
      'true and false',
      'false and true'
    ],
    correctIndex: 2,
    explanation: 'Loose equality (`==`) performs type coercion, converting the string "0" to number 0, resulting in `true`. Strict equality (`===`) checks both type and value without coercion (number vs string), resulting in `false`.',
    hint: 'Double equals coerces types; triple equals checks both type and value.',
    difficulty: 'beginner'
  },
  {
    id: 'q-js-4',
    skillId: 'js',
    skillName: 'JavaScript (ES6+)',
    subConcept: 'Const Immutability Nuance',
    prompt: 'What happens if you execute `const user = { name: "Alex" }; user.name = "Jordan";` in JavaScript?',
    type: 'mcq',
    options: [
      'TypeError: Assignment to constant variable is thrown.',
      'The property is successfully updated to "Jordan" because const prevents reassigning the identifier binding, not mutating object contents.',
      'The mutation silently fails without throwing an error.',
      'A runtime syntax error is thrown during parsing.'
    ],
    correctIndex: 1,
    explanation: '`const` creates an immutable variable binding to the memory reference. It does not make the referenced object deeply immutable. To freeze object properties, `Object.freeze()` is required.',
    hint: 'Does const freeze the pointer variable or the object properties inside heap memory?',
    difficulty: 'beginner'
  },
  {
    id: 'q-js-5',
    skillId: 'js',
    skillName: 'JavaScript (ES6+)',
    subConcept: 'Temporal Dead Zone (TDZ)',
    prompt: 'What occurs when attempting to access a `let` variable before its line of declaration?',
    type: 'mcq',
    options: [
      'It returns undefined because let is hoisted with an initial value of undefined.',
      'It throws a ReferenceError due to the Temporal Dead Zone (TDZ).',
      'It returns null.',
      'It throws a TypeError: variable is not a function.'
    ],
    correctIndex: 1,
    explanation: 'Variables declared with `let` and `const` are hoisted to the top of their block scope, but remain uninitialized in the Temporal Dead Zone (TDZ) until the evaluation reaches the declaration, throwing a ReferenceError if accessed early.',
    hint: 'Unlike `var` which yields `undefined`, modern block-scoped variables cannot be read before their declaration line.',
    difficulty: 'intermediate'
  },
  {
    id: 'q-react-1',
    skillId: 'react',
    skillName: 'React.js',
    subConcept: 'State Batching in React 18',
    prompt: 'In React 18, when multiple state setter functions are executed inside a setTimeout callback or fetch promise, what occurs by default?',
    type: 'mcq',
    options: [
      'React re-renders immediately after every individual state setter.',
      'React automatically batches updates together into a single coordinated re-render.',
      'An unhandled exception is thrown unless wrapped in flushSync.',
      'Batching only works inside native React synthetic event handlers.'
    ],
    correctIndex: 1,
    explanation: 'React 18 introduced automatic batching across all asynchronous contexts (promises, setTimeout, native event listeners), reducing redundant re-renders.',
    hint: 'React 18 expanded batching beyond synthetic event handlers to all execution contexts.',
    difficulty: 'intermediate'
  },
  {
    id: 'q-react-2',
    skillId: 'react',
    skillName: 'React.js',
    subConcept: 'useEffect Dependency Lifecycle',
    prompt: 'What happens if you omit the dependency array completely from a `useEffect` hook (`useEffect(() => { ... })`)?',
    type: 'mcq',
    options: [
      'The effect runs only once when the component mounts.',
      'The effect runs after every single render of the component.',
      'The effect never runs.',
      'React throws a compile-time build error.'
    ],
    correctIndex: 1,
    explanation: 'Passing no dependency array causes the effect to run on every single render. Passing an empty array `[]` runs it once on mount. Passing specific dependencies `[a, b]` runs it when those values change.',
    hint: 'An empty array `[]` means run once. What does omitting the array entirely mean?',
    difficulty: 'beginner'
  },
  {
    id: 'q-react-3',
    skillId: 'react',
    skillName: 'React.js',
    subConcept: 'List Reconciliation & Keys',
    prompt: 'Why is using array index as the `key` prop discouraged when rendering a dynamic list in React?',
    type: 'mcq',
    options: [
      'Because React only accepts UUID strings for the key prop.',
      'If items are reordered, inserted, or deleted, index keys can cause state bugs and incorrect component reuse.',
      'Array indices increase bundle size and trigger memory leaks.',
      'React will throw an uncatchable runtime error if keys are numbers.'
    ],
    correctIndex: 1,
    explanation: 'React uses keys to identify which items have changed, been added, or removed. If you use index as key and reorder or delete items, React reuses components with stale internal state.',
    hint: 'What happens to the array index of item #2 if you delete item #1 from the list?',
    difficulty: 'intermediate'
  },
  {
    id: 'q-react-4',
    skillId: 'react',
    skillName: 'React.js',
    subConcept: 'useMemo vs useCallback',
    prompt: 'What is the primary difference between React\'s `useMemo` and `useCallback` hooks?',
    type: 'mcq',
    options: [
      '`useMemo` caches the calculated result value of a function, while `useCallback` caches the function definition itself between renders.',
      '`useCallback` is exclusively for asynchronous API requests, while `useMemo` is for synchronous loops.',
      '`useMemo` runs on the server side, whereas `useCallback` runs only on the client.',
      'There is no difference; they are aliases for the same hook.'
    ],
    correctIndex: 0,
    explanation: '`useCallback(fn, deps)` is equivalent to `useMemo(() => fn, deps)`. `useCallback` caches the function reference to prevent unnecessary child re-renders, while `useMemo` caches expensive computed values.',
    hint: 'One memoizes a returned value; the other memoizes the function reference itself.',
    difficulty: 'intermediate'
  },
  {
    id: 'q-react-5',
    skillId: 'react',
    skillName: 'React.js',
    subConcept: 'Prop Drilling Prevention',
    prompt: 'When deeply nested child components need access to global theme or auth state without passing props through intermediate layers, which React feature is best suited?',
    type: 'mcq',
    options: [
      'React Error Boundaries',
      'React Context API (or Zustand / Redux)',
      'Inline dangerouslySetInnerHTML',
      'Direct window object mutations'
    ],
    correctIndex: 1,
    explanation: 'The React Context API (and dedicated state management tools like Zustand) allows state to be provided at a high level and consumed anywhere in the subtree without prop drilling.',
    hint: 'Which React API provides a Provider and Consumer or useContext hook?',
    difficulty: 'beginner'
  },
  {
    id: 'q-node-1',
    skillId: 'node',
    skillName: 'Node.js & Express',
    subConcept: 'Express Middleware Pipeline',
    prompt: 'In Express.js, what must a custom middleware function invoke to pass control to the subsequent handler in the pipeline?',
    type: 'mcq',
    options: [
      'res.continue()',
      'next()',
      'process.nextTick()',
      'return true;'
    ],
    correctIndex: 1,
    explanation: 'Express middleware functions receive `(req, res, next)` arguments. If the middleware does not end the request-response cycle, it must call `next()` to pass control to the next middleware function.',
    hint: 'What is the standard third parameter passed to Express middleware callbacks?',
    difficulty: 'beginner'
  },
  {
    id: 'q-node-2',
    skillId: 'node',
    skillName: 'Node.js & Express',
    subConcept: 'REST HTTP Status Codes',
    prompt: 'When a RESTful POST endpoint successfully creates a new database record, which HTTP status code is the standard best practice to return?',
    type: 'mcq',
    options: [
      '200 OK',
      '201 Created',
      '204 No Content',
      '302 Found'
    ],
    correctIndex: 1,
    explanation: 'HTTP 201 Created indicates that the request has succeeded and led to the creation of a new resource, typically including a Location header or the created entity in the response body.',
    hint: '200 is generic success; which specific 2xx code signifies a new resource was created?',
    difficulty: 'beginner'
  },
  {
    id: 'q-node-3',
    skillId: 'node',
    skillName: 'Node.js & Express',
    subConcept: 'CORS Preflight Mechanism',
    prompt: 'Which HTTP request method is sent by modern web browsers as a CORS preflight check before making a non-simple cross-origin request?',
    type: 'mcq',
    options: [
      'HEAD',
      'GET',
      'OPTIONS',
      'CONNECT'
    ],
    correctIndex: 2,
    explanation: 'Browsers automatically issue an `OPTIONS` preflight request containing `Access-Control-Request-Method` headers to verify that the server permits the cross-origin operation before sending the actual request.',
    hint: 'Which HTTP verb asks the server what communication options are available for the target resource?',
    difficulty: 'intermediate'
  },
  {
    id: 'q-node-4',
    skillId: 'node',
    skillName: 'Node.js & Express',
    subConcept: 'Event-Driven Architecture',
    prompt: 'What core architectural pattern does Node.js\'s native `EventEmitter` class implement?',
    type: 'mcq',
    options: [
      'Model-View-Controller (MVC)',
      'Publisher-Subscriber (Observer Pattern)',
      'Singleton Database Connection Pool',
      'Factory Builder Pattern'
    ],
    correctIndex: 1,
    explanation: 'The `EventEmitter` implements the Observer (Publisher-Subscriber) pattern, allowing objects to emit named events that cause registered listener functions to be called synchronously in order.',
    hint: 'When one component emits an event and multiple listeners subscribe to it, what pattern is that?',
    difficulty: 'intermediate'
  },
  {
    id: 'q-ts-1',
    skillId: 'typescript',
    skillName: 'TypeScript',
    subConcept: 'Interface Declaration Merging',
    prompt: 'Which feature can TypeScript `interface` perform that `type` aliases cannot?',
    type: 'mcq',
    options: [
      'Union types (`A | B`)',
      'Tuple definitions (`[string, number]`)',
      'Declaration merging (extending by redeclaring with the same name)',
      'Primitive aliases (`type ID = string`)'
    ],
    correctIndex: 2,
    explanation: 'Declaration merging allows multiple `interface` definitions with the same name in the same scope to automatically merge their member declarations. `type` aliases cannot be re-opened or merged.',
    hint: 'If you declare `interface User { a: string }` and then declare `interface User { b: number }`, what happens?',
    difficulty: 'advanced'
  },
  {
    id: 'q-ts-2',
    skillId: 'typescript',
    skillName: 'TypeScript',
    subConcept: 'Unknown vs Any Safety',
    prompt: 'Why is TypeScript\'s `unknown` type safer than `any`?',
    type: 'mcq',
    options: [
      '`unknown` disables the compiler type checker entirely.',
      '`unknown` forbids calling methods or accessing properties on the variable until you perform type narrowing.',
      '`unknown` can only hold primitive numbers and booleans.',
      '`unknown` automatically converts all values into JSON strings.'
    ],
    correctIndex: 1,
    explanation: '`any` completely turns off type checking, letting you call non-existent methods. `unknown` represents any value, but TypeScript forces you to narrow the type (via `typeof`, `instanceof`, or custom type guards) before performing operations.',
    hint: 'You cannot do `val.foo()` on an `unknown` variable without checking its type first.',
    difficulty: 'intermediate'
  },
  {
    id: 'q-ts-3',
    skillId: 'typescript',
    skillName: 'TypeScript',
    subConcept: 'Generics Purpose',
    prompt: 'What is the primary benefit of using Generics (`<T>`) in TypeScript functions?',
    type: 'mcq',
    options: [
      'They force the JavaScript runtime to allocate generic C++ memory pointers.',
      'They allow functions to work with multiple data types while maintaining full compile-time type safety.',
      'They automatically serialize data into GraphQL schemas.',
      'They prevent functions from being called asynchronously.'
    ],
    correctIndex: 1,
    explanation: 'Generics allow you to write reusable, flexible code that works with a variety of types while preserving complete type relationships between parameters and return types.',
    hint: 'Generics provide type-safe flexibility without resorting to `any`.',
    difficulty: 'intermediate'
  },
  {
    id: 'q-sys-1',
    skillId: 'system-design',
    skillName: 'System Design & Scalability',
    subConcept: 'Horizontal vs Vertical Scaling',
    prompt: 'What is the primary difference between horizontal scaling and vertical scaling?',
    type: 'mcq',
    options: [
      'Horizontal scaling adds more machines/nodes to the pool; vertical scaling adds more CPU/RAM to an existing machine.',
      'Vertical scaling is for SQL databases; horizontal scaling is only for CSS stylesheets.',
      'Horizontal scaling increases single-core CPU frequency; vertical scaling distributes network cables.',
      'There is no difference; both mean moving to AWS.'
    ],
    correctIndex: 0,
    explanation: 'Horizontal scaling (scaling out) involves adding more individual server instances behind a load balancer. Vertical scaling (scaling up) involves upgrading the compute, memory, or disk of a single existing server.',
    hint: 'Scaling "out" vs scaling "up".',
    difficulty: 'beginner'
  },
  {
    id: 'q-sys-2',
    skillId: 'system-design',
    skillName: 'System Design & Scalability',
    subConcept: 'Cache-Aside Pattern',
    prompt: 'In the Cache-Aside (Lazy Loading) caching pattern, what occurs when an application experiences a cache miss?',
    type: 'mcq',
    options: [
      'The request is rejected with a 504 Gateway Timeout.',
      'The application reads the data from the database, writes it into the cache, and returns it to the client.',
      'The cache drops all existing keys and flushes its memory.',
      'The database automatically queries the browser\'s local storage.'
    ],
    correctIndex: 1,
    explanation: 'In cache-aside, the application first checks the cache. On a miss, it queries the underlying database, populates the cache with the fetched record for future requests, and returns the response.',
    hint: 'If it is not in the cache, where do you get it from, and what do you do with it for the next caller?',
    difficulty: 'intermediate'
  },
  {
    id: 'q-sys-3',
    skillId: 'system-design',
    skillName: 'System Design & Scalability',
    subConcept: 'Database Sharding',
    prompt: 'What is database sharding?',
    type: 'mcq',
    options: [
      'Creating a real-time read replica of the entire primary database.',
      'Horizontally partitioning rows of a dataset across multiple separate database servers based on a shard key.',
      'Encrypting database tables into broken binary pieces for security.',
      'Deleting old historical data to free up disk capacity.'
    ],
    correctIndex: 1,
    explanation: 'Sharding is a database architecture pattern where large tables are split horizontally into distinct pieces (shards) across multiple database instances, usually partitioned by a shard key like user_id.',
    hint: 'Sharding splits table rows across multiple distinct database instances.',
    difficulty: 'advanced'
  },
  {
    id: 'q-sys-4',
    skillId: 'system-design',
    skillName: 'System Design & Scalability',
    subConcept: 'API Idempotency',
    prompt: 'In RESTful API design, an operation is considered "idempotent" if:',
    type: 'mcq',
    options: [
      'It can only be called by authenticated administrative users.',
      'Making multiple identical requests has the same intended outcome on the system state as making a single request.',
      'It responds within 5 milliseconds.',
      'It modifies data on every single request without checking previous records.'
    ],
    correctIndex: 1,
    explanation: 'An idempotent HTTP method (like GET, PUT, or DELETE) produces the exact same server state whether executed once or 10 times consecutively. POST is generally not idempotent because multiple requests create multiple resources.',
    hint: 'If you delete an item once or delete it 5 times, is the final state of the database the same?',
    difficulty: 'intermediate'
  },
  {
    id: 'q-sec-1',
    skillId: 'sql',
    skillName: 'SQL & Relational DB',
    subConcept: 'SQL Injection Prevention',
    prompt: 'What is the most effective technique for preventing SQL injection attacks in web applications?',
    type: 'mcq',
    options: [
      'Concatenating user input with single quotes inside SQL strings.',
      'Using parameterized queries (prepared statements) or an ORM that separates query structure from data.',
      'Running the database server on port 80 instead of 5432.',
      'Restricting input fields to lowercase letters with regex.'
    ],
    correctIndex: 1,
    explanation: 'Parameterized queries (prepared statements) ensure that the database engine treats user input strictly as data parameters, never as executable SQL commands, neutralizing SQL injection vulnerabilities.',
    hint: 'Prepared statements treat inputs as literal data parameters, never executable code.',
    difficulty: 'beginner'
  }
];
